### ISSUE TITLE
Use RuntimeException iso checked exception

### ISSUE THREAD

**Issue by alicanalbayrak** [ayhanugurlu/jdbi-example#1]
Since it's an unrecoverable action, its recommended to use runtime exception.

https://github.com/ayhanugurlu/jdbi-example/blob/c071e16182d097347570a9d0e55f0ded77ba03b3/src/main/java/com/au/example/jdbiexample/exception/NotFoundException.java#L4

**Comment by ayhanugurlu** [comment]
No, runtime exception is not recommended for this type development.
